import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import KeriNav from "./component/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    absolute:"Create Next App",
    default:"Create Next App title default",
    template:"%s  Create Next App"

  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <KeriNav />
        {children}
        </body>
    </html>
  );
}
